export const SERIES = [
  'Breaking Bad',
  'Game of Thrones',
  'Chernobyl',
  'Band of Brothers',
  'Sherlock',
  'The Wire',
  'Rick and Morty',
  'Friends',
  'The Sopranos',
  'True Detective',
  'Stranger Things',
  'Avatar: The Last Airbender',
  'The Office',
  'Firefly',
  'Black Mirror',
  'Fargo',
  'Death Note',
  'Dexter',
  'House of Cards',
  'Narcos',
  'Westworld',
  'Peaky Blinders',
  'House M.D.',
  'The Simpsons',
  'Seinfeld',
  'South Park',
  'Fullmetal Alchemist: Brotherhood',
  'Dark',
  'Better Call Saul',
  'Arrested Development',
  'Daredevil',
  'Leyla and Mecnun',
  'It\'s Always Sunny in Philadelphia',
  'Twin Peaks',
  'Vikings',
  'Suits',
  'Attack on Titan',
  'Sons of Anarchy',
  'Batman: The Animated Series',
  'The Mandalorian',
  'The Walking Dead',
  'Mr. Robot',
  'TVF Pitchers',
  'How I Met Your Mother',
  'Freaks and Geeks',
  'Supernatural',
  'Downton Abbey',
  'The Boys',
  'Parks and Recreation',
  'The Haunting of Hill House',
  'Rome',
  'Mad Men',
  'Battlestar Galactica',
  'The Twilight Zone',
  'Lost',
  'Mindhunter',
  'Doctor Who',
  'The X Files',
  'Shameless',
  'Cowboy Bebop',
  'Prison Break',
  'Modern Family',
  'One Punch Man: Wanpanman',
  'When They See Us',
  'Koombiyo',
  'Hannibal',
  'Spartacus',
  'Six Feet Under',
  'Community',
  'The Big Bang Theory',
  'The Crown',
  'Money Heist',
  'Gravity Falls',
  'Dragon Ball Z',
  'Archer',
  'BoJack Horseman',
  'The Punisher',
  'Curb Your Enthusiasm',
  'Homeland',
  'Boardwalk Empire',
  'This Is Us',
  'Pride and Prejudice',
  'Fringe',
  'The Handmaid\'s Tale',
  'Futurama',
  'Brooklyn Nine-Nine',
  'Oz',
  'Big Little Lies',
  'Fawlty Towers',
  'The Chosen',
  'Fleabag',
  'The Newsroom',
  'The West Wing',
  'Hunter x Hunter',
  'Scrubs',
  'The IT Crowd',
  'Star Trek: The Next Generation',
  'Only Fools and Horses',
  'Ozark',
  'Spartacus: Gods of the Arena',
  'Silicon Valley',
  'Person of Interest',
  'The Marvelous Mrs. Maisel',
  'Deadwood',
  'The Shield',
  'Entourage',
  'Sacred Games',
  'Luther',
  'Sahsiyet',
  'The Night Of',
  'The Witcher',
  'Justified',
  'One Piece',
  'Blackadder Goes Forth',
  'Yeh Meri Family',
  'Naruto: Shippuden',
  'Californication',
  '24',
  'Flames',
  'Adventure Time',
  'The Office',
  'Kota Factory',
  'The Expanse',
  'Family Guy',
  'Cobra Kai',
  'Love, Death & Robots',
  'Outlander',
  'Battlestar Galactica',
  'Orange Is the New Black',
  'Lucifer',
  'Steins;Gate',
  'Taboo',
  'Sex Education',
  'Over the Garden Wall',
  'Sense8',
  'After Life',
  'Louie',
  'The Legend of Korra',
  'Bron/Broen',
  'Friday Night Lights',
  'Dekalog',
  'Undercover',
  'Broadchurch',
  'College Romance',
  'Peep Show',
  'American Horror Story',
  'Spaced',
  'Banshee',
  'Stargate SG-1',
  'Atlanta',
  'The Americans',
  'Code Geass: Lelouch of the Rebellion',
  'The Inbetweeners',
  'Fullmetal Alchemist',
  'American Crime Story',
  'Orphan Black',
  'The Last Kingdom',
  'The Pacific',
  'Ramayan',
  'Buffy the Vampire Slayer',
  'Chuck',
  'Blackadder II',
  'The Mentalist',
  'Twin Peaks',
  'Black Books',
  'Das Boot',
  'Dragon Ball',
  'White Collar',
  'Blackadder the Third',
  'Criminal Minds',
  'Billions',
  'The Originals',
  'That \'70s Show',
  '30 Rock',
  'Anne with an E',
  'Penny Dreadful',
  'Psych',
  'Ash vs Evil Dead',
  'Unbelievable',
  'Legion',
  'Poirot',
  'Neon Genesis Evangelion',
  'Generation Kill',
  'Castle',
  'The Blacklist',
  'Killing Eve',
  'Altered Carbon',
  'Father Ted',
  'The End of the F***ing World',
  'The Good Place',
  'Ray Donovan',
  'The Leftovers',
  'Gomorrah',
  'Samurai Jack',
  'Skam',
  'The Killing',
  'Narcos: Mexico',
  'Bates Motel',
  'The Knick',
  'Star Trek',
];
